package project.cn.edu.tongji.sse.nowfitness.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import project.cn.edu.tongji.sse.nowfitness.model.StepModel;

/**
 * Created by LK on 2018/12/11.
 */

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP_MODEL".
*/
public class StepModelDao extends AbstractDao<StepModel, Long> {

    public static final String TABLENAME = "STEP_MODEL";

    /**
     * Properties of entity StepModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, int.class, "userId", false, "USER_ID");
        public final static Property Step = new Property(2, String.class, "step", false, "STEP");
        public final static Property Today = new Property(3, String.class, "today", false, "TODAY");
    }


    public StepModelDao(DaoConfig config) {
        super(config);
    }
    
    public StepModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"STEP\" TEXT," + // 2: step
                "\"TODAY\" TEXT);"); // 3: today
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StepModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String step = entity.getStep();
        if (step != null) {
            stmt.bindString(3, step);
        }
 
        String today = entity.getToday();
        if (today != null) {
            stmt.bindString(4, today);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StepModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String step = entity.getStep();
        if (step != null) {
            stmt.bindString(3, step);
        }
 
        String today = entity.getToday();
        if (today != null) {
            stmt.bindString(4, today);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StepModel readEntity(Cursor cursor, int offset) {
        StepModel entity = new StepModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // step
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // today
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StepModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getInt(offset + 1));
        entity.setStep(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setToday(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StepModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StepModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StepModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
